dist: xenial
sudo: required
before_install:
  # install latest docker and enable experimental features
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  # start docker
  - sudo service docker start
install:
  - docker --version
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  # prepare builder
  - docker buildx create --name xbuilder --use
language: bash
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=monstrenyatko/openvpn-client
script:
  # build image
  - ./build.sh "$REPO:$COMMIT"
  # get release name
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # tag and push
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      # login
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # push
      ./build.sh "$REPO:$COMMIT" "--push"
      ./build.sh "$REPO:$TRAVIS_BUILD_NUMBER" "--push"
      ./build.sh "$REPO:$TAG" "--push"
    fi
notifications:
  email:
    on_success: change
    on_failure: always
